### ISSUE TITLE
sporadic issue with "\r\n" in field result

### ISSUE THREAD

**Issue by quirrel1002** [kawansoft/aceql-http#6] opened 2020-03-20 16:58 UTC
Hello,
I currently run quries with lots of results sets and field per "row" over aceql.
basically it works fine.
Only from time to time I get "r\n" added to a field value which totally disturbs reading and conversion of values. For e.g. Datetime, this results in wrong format error, for "Text" type, the stream cannot be opened because the file name contains an "\r\n".
Suprisingly a rerun of similar query with reduced number of results or different "parameters" works as expected.

Do you have in hint what could cause that issue?
Regards,
Tobias

**Comment by ndepomereu** [comment] 2020-03-20 18:06
Hi Tobias,
Very weird, I will try to reproduce.
Please send sample code of both cases. 
Also please give your server env info (OS, database, etc.).

**Comment by QuasiQA** [comment] 2020-03-20 18:17
Can confirm that same issue reproduced occasionally both on Linux and on Windows.
Randomly reproduced in case of big amount of rows in response.

As a workaround we used replace of that symbols with an empty string

**Comment by ndepomereu** [comment] 2020-03-20 21:02
QuasiQA, 
Do you use an AceQK client SDK? Which one?
Otherwise, you just parse the JSON?

**Comment by QuasiQA** [comment] 2020-03-20 22:07
Nicolas, 
I use only AceQL server, not the client SDK.
json with additional \n symbol is being provided by AceQL server

In my case JSON response is being parsed by another tool, but this shouldn't be matter, since json provided by AceQL server

**Comment by quirrel1002** [comment] 2020-03-21 09:26
hello,

> Also please give your server env info (OS, database, etc.).

so my specific environment was AceQL "Server" on windows 10 and MS SQL Standard database server on windows 10.
I use SQL c# client implementation.

> Please send sample code of both cases.

The queries are generated in my case so I cannot give you example for both. I reproduced one case with the "AceQL.Client.WinFormTest" project you provided and that is helpful for testing.
The query I used was 
```
"SELECT t0.IpID as t0_IpID, t0.IpAttributeID as t0_IpAttributeID, 
             t0.MsiID as t0_MsiID, t0.MsiAttributeID as t0_MsiAttributeID, 
             t0.MsiPackageID as t0_MsiPackageID,t0.IpPackageID as t0_IpPackageID, 
             t0.MsiVersion as t0_MsiVersion, t0.IpVersion as t0_IpVersion, 
             ISNULL(t0.MsiAttributeValue,'') as t0_MsiAttributeValue, 
             t0.IpAttributeValue as t0_IpAttributeValue, t0.MsiDeleted as t0_MsiDeleted, 
             t0.MsiBuildType as t0_MsiBuildType, 
             t0.MsiProcessingState as t0_MsiProcessingState, 
             t0.MsiTFSID as t0_MsiTFSID, t0.MsiTypeID as t0_MsiTypeID, 
             ISNULL(t0.MsiCreationDate,'') as t0_MsiCreationDate, 
             ISNULL(t0.MsiModifiedDate,'') as t0_MsiModifiedDate, 
             ISNULL(t0.MsiChangedBy,'') as t0_MsiChangedBy,
             t0.IpDeleted as t0_IpDeleted, t0.IpBuildType as t0_IpBuildType, 
             t0.IpProcessingState as t0_IpProcessingState, 
             t0.IpTFSID as t0_IpTFSID, t0.IpTypeID as t0_IpTypeID, 
             t0.IpCreationDate as t0_IpCreationDate, t0.IpModifiedDate as t0_IpModifiedDate,
             t0.IpChangedBy as t0_IpChangedBy
 FROM [MSI_IP] t0 
 WHERE (ipPackageID = 6864 AND ipTypeID = 5 AND ipDeleted = 0 AND ipVersion LIKE '%')";
```
this "only" returned 17 rows, and in 10th row the "IpModifiedDate" (DATETIME) contained an extra "\r\n" beore the last digit, resulting in format error.
Also this works when I comment `/*t0.IpDeleted as t0_IpDeleted,*/ ` without that extra character.

I hope that helps in finding any issue. 
can you also tell me how the workaround mentioned by @QuasiQA could applied when using the c# Client SDK?

**Comment by ndepomereu** [comment] 2020-03-25 17:23
Hi,

I could not reproduce the problem.
I assume the bug is due to the usage of an olf version of javax.json JSON library.
We will upgrade for the next 5.0 version due this week or the beginning of next at last.

**Comment by quirrel1002** [comment] 2020-03-25 18:50
Hello,
thanks for the update. I will take the newest version ones it is released next week and give you an update.

**Comment by quirrel1002** [comment] 2020-04-06 08:43
hi,
as I am a little stuck with this for now: Is there a change of testing an BETA version of V5.0? To get a feeling whether I would need a work of workaround or issue can be solved?

**Comment by ndepomereu** [comment] 2020-04-06 09:14
Hi Tobias,

Version 5.0 should be ready in the next 48 hours.

For version 4.1, I suggest that you try changing  in your deploy the jars of glassfish jars v1.0.4 by those of version 1.1.4 accessible via Maven Central nd give a try: 

		<dependency>
			<groupId>org.glassfish</groupId>
			<artifactId>javax.json</artifactId>
			<version>1.1.4</version>
		</dependency>

**Comment by ndepomereu** [comment] 2020-04-07 08:05
Hi,

We have found the "\r\n" problem.
When the server response line is too long it can be plitted in severous lines when JSON pretty-printing is off.

Turnaround is to systematically set pretty printing  on all SELECT call:

1) Command line / No SDK:
Pass -`-data "pretty_printing=true"` on each select call:
ex: 
```
curl ^
--data-urlencode "sql=select * from customer" ^
--data "pretty_printing=true" ^
https://www.aceql.com:9443/aceql/session/emblc1sfkc0uhfb3t1fj6qbbu4/execute_query
```
2) Java Client SDK
Set Pretty Printing to true after Connection creation:
```
	Connection connection = new AceQLConnection(url, database, username, password);
	((AceQLConnection)connection).setPrettyPrinting(true);
```
3) C# Client SDK
Set Pretty Printing to true after Connection creation:
```
AceQLConnection connection = new AceQLConnection(connectionString)
connection.PrettyPrinting = true;
```

Python will be fixed in next release.

**Comment by ndepomereu** [comment] 2020-04-07 08:10
We will of course also  fix that in upcoming 5.0 release  (pretty printing will always be on, so that threrz is nothing to do on client side).

**Comment by quirrel1002** [comment] 2020-04-08 07:24
Hi Nicloas,
thanks a lot for the correction and hints. I really appreciate quick response and bugfix already in place for c# client.
wish you a happy easter then

**Comment by quirrel1002** [comment] 2020-04-10 09:55
so I checked newest c# client Version 5.0 of the server and the reported issue is gone.
unfortunately I have an similar issue now when I try to execute the SQL query 
`SELECT t0.Id as t0_id, t0.PackageInstanceId1 as t0_PackageInstanceId1, t0.PackageInstanceId2 as t0_PackageInstanceId2, t0.RelationId as t0_RelationId, t0.IsForward as t0_IsForward, t0.AttributeId as t0_AttributeId FROM [PackageDependency] t0 WHERE (t0.PackageInstanceID1 = 716165)`

the error from the trace is: 
`Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: 1. Path 'query_rows[0].row_2907[1].t0_packageinstanceid1', line 58140, position 0.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
   at Newtonsoft.Json.JsonTextReader.Read()
   at AceQL.Client.Api.Util.RowCounter.Count()
   at AceQL.Client.Api.AceQLCommand.<ExecuteQueryAsStatementAsync>d__17.MoveNext()`

the respective JSON looks like:

```
                {
                    "t0_packageinstanceid1": 7
16165    >>>(this is line 58140)
                },
```
The query retrieves 2914 rows.

Suprisingly, changing the query to e.g. 
`SELECT t0.Id **as t0id**, t0.PackageInstanceId1 as t0_PackageInstanceId1, t0.PackageInstanceId2 as t0_PackageInstanceId2, t0.RelationId as t0_RelationId, t0.IsForward as t0_IsForward, t0.AttributeId as t0_AttributeId FROM [PackageDependency] t0 WHERE (t0.PackageInstanceID1 = 716165)`
works without issues.
Any hint on where this issue might come from is welcome!?!

Happy easter!

**Comment by ndepomereu** [comment] 2020-04-10 10:27
Hi Tobias,
Do you have very long lines in the JSON results? (Example : text field).
What is the length of  this line: 
```
                {
                    "t0_packageinstanceid1": 7
16165    >>>(this is line 58140)
                } 
```

**Comment by quirrel1002** [comment] 2020-04-10 11:25
So I have the file not on hand, but this time it had not long lines like in text fields if I remember correctly. I can add a longer part of the json result file later today hopefully.

**Comment by ndepomereu** [comment] 2020-04-10 11:57
Ok, please send the part thats splits with \r\n next time.
I will try to reproduce and will  make a fix that uses Base64 transport for fields for beginning of next week.

**Comment by quirrel1002** [comment] 2020-04-10 12:39
So, in my example
`"t0_packageinstanceid1": 7 ` should be `"t0_packageinstanceid1": 716165` after 7 the line break (\r\n) makes troubles....

**Comment by ndepomereu** [comment] 2020-04-10 13:21
Thanks, I was able to reproduce and understand more clearly the problem! 
I will make some tests now, I tell later today about the possible fix.

**Comment by ndepomereu** [comment] 2020-04-10 17:59
Hi,
New version 5.0.1 fixes the "\r\n"problem:
SELECT calls with more than 20Kb output could randomly fail, because of a bug in Glassfish javax.json JSON parser that inserts a \r\n at each 20Kb output.This has been fixed by calling JsonGenerator.flush() on each SQL row dump.

**Comment by QuasiQA** [comment] 2020-04-10 18:20
Thanks a lot Nicolas!

**Comment by ndepomereu** [comment] 2020-04-10 18:39
Welcome!

**Comment by quirrel1002** [comment] 2020-04-10 18:46
Thanks for the quick response and solution. I will test on monday and let you know the result.

**Comment by quirrel1002** [comment] 2020-04-13 08:52
so, I was able to make first tests today with V5.0.1 and it looks very good from my side.
Thanks for solution

**Comment by ndepomereu** [comment] 2020-04-14 10:55
Welcome! I close the issue then.

**Closed by ndepomereu** 2020-04-14 10:55 UTC
